#!/bin/bash

# Configuration
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Verify ROM_FOLDER is set
if [ -z "$ROM_FOLDER" ]; then
    echo -e "${RED}ERROR: ROM_FOLDER environment variable not set!${NC}"
    echo "Usage: This script should be called from the main build script"
    exit 1
fi

# Set paths
TARGET_SYSTEM="${ROM_FOLDER}/system/system"
TARGET_XML="${TARGET_SYSTEM}/etc/floating_feature.xml"
SCRIPT_DIR="${BASE_DIR}/devices/y2q/scripts/"

# Verify target XML exists
if [ ! -f "$TARGET_XML" ]; then
    echo -e "${YELLOW}WARNING: floating_feature.xml not found, creating new one...${NC}"
    mkdir -p "$(dirname "$TARGET_XML")"
    touch "$TARGET_XML"
fi

# Load helper
HELPER_SCRIPT="${BASE_DIR}/ishihara/utils/ff_helper.sh"
if [ ! -f "$HELPER_SCRIPT" ]; then
    echo -e "${RED}ERROR: Helper script not found at $HELPER_SCRIPT${NC}"
    exit 1
fi

source "$HELPER_SCRIPT" || {
    echo -e "${RED}ERROR: Failed to load XML helper${NC}"
    exit 1
}

# Initialize XML file
echo -e "\n${GREEN}[+] Configuring floating features...${NC}"
init_xml_file "$TARGET_XML" || {
    echo -e "${RED}ERROR: Failed to initialize XML file${NC}"
    exit 1
}

# Floating Feature Tags
declare -A FEATURE_TAGS=(
    ["SEC_FLOATING_FEATURE_LAUNCHER_CONFIG_ANIMATION_TYPE"]="HighEnd"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_SMART_LASSO"]="TRUE"
    ["SEC_FLOATING_FEATURE_LCD_SUPPORT_EXTRA_BRIGHTNESS"]="TRUE"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_AI_EXPANSION"]="AI_Timelapse,singletake.hidt.support.on,singletake.capture.support.off,singletake.video_res.config.fhd"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_COLOR_ENGINE_VERSION"]="V2"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_FACE_CLUSTER_VERSION"]="SRCB_V4"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_UPDATE"]="None"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_IMAGE_TAGGER_VERSION"]="V715"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_LIVEFOCUS_EFFECT_DUAL_BOKEH"]="BLUR,EFFECT,BIGBOKEH,PORTRAIT,RELIGHT,REFOCUS,LIGHT360"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_PET_CLUSTER_VERSION"]="V713"
    ["SEC_FLOATING_FEATURE_GALLERY_CONFIG_ZOOM_TYPE"]="ZOOM_2K"
    ["SEC_FLOATING_FEATURE_GALLERY_SUPPORT_LOCATION_POI"]="TRUE"
    ["SEC_FLOATING_FEATURE_GALLERY_SUPPORT_STORYEDITOR"]="0"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_IMAGE_CLIPPER"]="TRUE"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_OBJECT_ERASER"]="TRUE"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_REFLECTION_ERASER"]="TRUE"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_SHADOW_ERASER"]="TRUE"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_SPOT_FIXER"]="TRUE"
    ["SEC_FLOATING_FEATURE_GENAI_SUPPORT_STYLE_TRANSFER"]="TRUE"
    ["SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_FUNCTION_KEY_MENU"]="TRUE"
    ["SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_MOTION"]="TRUE"
    ["SEC_FLOATING_FEATURE_VOICERECORDER_CONFIG_DEF_MODE"]="normal,interview,voicememo"
    ["SEC_FLOATING_FEATURE_SAIV_SUPPORT_AI_REVITAL"]="TRUE"
    ["SEC_FLOATING_FEATURE_MMFW_SUPPORT_AI_MASTERINGNET"]="TRUE"
    ["SEC_FLOATING_FEATURE_MMFW_SUPPORT_AI_UPSCALER"]="TRUE"
    ["SEC_FLOATING_FEATURE_MMFW_SUPPORT_APE_FORMAT"]="TRUE"
    ["SEC_FLOATING_FEATURE_AUDIO_CONFIG_INTERPRETER"]="1"
	["SEC_FLOATING_FEATURE_SYSTEM_CONFIG_SIOP_POLICY_FILENAME"]="siop_y2q_sm8250"
	["SEC_FLOATING_FEATURE_CAMERA_CONFIG_VENDOR_LIB_INFO"]="beauty.samsung.v4,face_landmark.arcsoft.v2_1,facial_attribute.samsung.v1,super_resolution.arcsoft.v2_1,super_night.mpi.v2,event_detection.samsung.v2,food.samsung.v1,selfie_correction.samsung.v1,mfhdr.arcsoft.v1,llhdr.arcsoft.v1,swuwdc.arcsoft.v1,human_tracking.arcsoft.v2_1,single_bokeh.samsung.v2,human_segmentation.samsung.v2,smart_scan.samsung.v2,dual_bokeh.samsung.v1_1,image_enhance.arcsoft.v1,high_res.arcsoft.v1,localtm.samsung.v1_1,scene_detection.samsung.v1"
	["SEC_FLOATING_FEATURE_CAMERA_CONFIG_MEMORY_USAGE_LEVEL"]="3"
	["SEC_FLOATING_FEATURE_CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT"]="85"
	["SEC_FLOATING_FEATURE_CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE"]="-1"
	["SEC_FLOATING_FEATURE_CAMERA_CONFIG_LLHDR_PROCESSING_TIMEOUT"]="2000"
	["SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_EAGLE_EYE"]="FALSE"
	["SEC_FLOATING_FEATURE_LCD_CONFIG_HFR_MODE"]="3"
	["SEC_FLOATING_FEATURE_LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE"]="30,48,60,96,120"
    ["SEC_FLOATING_FEATURE_SETTINGS_CONFIG_BRAND_NAME"]="Galaxy S20+ 5G"
    ["SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DEFAULT_FONT_SIZE"]="2"
    ["SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DEFAULT_POCKET_MODE"]="1"
    ["SEC_FLOATING_FEATURE_SETTINGS_CONFIG_ELECTRIC_RATED_VALUE"]="DC 9 V; 2.77 A"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_ACTION_CLASSIFIER"]="1,0"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_AI_HIGH_RESOLUTION_MAX_CAPTURE"]="1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_AVATAR_MAX_FACE_NUM"]="1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_BOKEH"]="-1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_MACRO"]="-1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE2"]="-1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_BINNING"]="-1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP"]="-1"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_UW"]="2"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CAMID_WIDE"]="0"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_CORE_VERSION"]="v2"
    ["SEC_FLOATING_FEATURE_CAMERA_CONFIG_UW_DISTORTION_CORRECTION"]="0,109,2,19010101,0,0,0,0,0,0"
    ["SEC_FLOATING_FEATURE_AUDIO_SUPPORT_DC_MOTOR_HAPTIC_FEEDBACK"]="TRUE"
    ["SEC_FLOATING_FEATURE_COMMON_CONFIG_MDNIE_MODE"]="65303"
    ["SEC_FLOATING_FEATURE_COMMON_CONFIG_DYN_RESOLUTION_CONTROL"]="WQHD,FHD,HD"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_QUALCOMM_BLEND_RMSSI_HI"]="0"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_QUALCOMM_BLEND_SINR_HI"]="0"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_QUALCOMM_GOODCH_RMSSITH"]="-110"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_RICHWAVE_SEEK_DC"]="4"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_RICHWAVE_SEEK_QA"]="20"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SLSI_BLENDCOEF"]="3172"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SLSI_IFCOUNT1"]="4800"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SLSI_IFCOUNT2"]="5600"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SOFTMUTE_PATH"]="Speaker"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SPRD_FREQ_OFFSET"]="1500"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SPRD_NOISE_PWR"]="176"
    ["SEC_FLOATING_FEATURE_FMRADIO_CONFIG_SPRD_PILOT_PWR"]="400"
    ["SEC_FLOATING_FEATURE_FMRADIO_REMOVE_AF_MENU"]="TRUE"
    ["SEC_FLOATING_FEATURE_FMRADIO_SUPPORT_EXTERNAL_RADIO_CHIPSET"]="TRUE"
    ["SEC_FLOATING_FEATURE_FMRADIO_SUPPORT_SOFTMUTE"]="TRUE"
)

# Process tags
echo -e "${YELLOW}[+] Updating feature tags...${NC}"
for tag in "${!FEATURE_TAGS[@]}"; do
    echo -e "  Processing: ${tag}"
    modify_feature_tag "$tag" "${FEATURE_TAGS[$tag]}" "$TARGET_XML" || {
        echo -e "${RED}ERROR: Failed to modify tag: ${tag}${NC}"
    }
done

# Verification
echo -e "\n${GREEN}[✓] Floating features configuration complete${NC}"
echo -e "${YELLOW}Modified features in ${TARGET_XML}:${NC}"
grep -E '<SEC_FLOATING_FEATURE_' "$TARGET_XML" | sed 's/^/  /'

exit 0
